### ISSUE TITLE
'start' parameter seems to not working

### ISSUE THREAD

**Issue by SantaHey** [arrrlo/Google-Images-Search#115]
I want to get the second result of a search without uselessly use my quota with "num" parameter (which using quickly my quota).

So I wanted to use 'start' parameter but it seems to not working, it returns me the same image each time.

What this code is doing ?
![image](https://user-images.githubusercontent.com/33598903/130485537-ed2c54b7-0c13-4492-bd51-ffe07b61b500.png)

Why not using this ?
`search_params.get('start') or start`

**Comment by arrrlo** [comment]
Can you please share you code where you "uselessly use my quota with "num" parameter"?

**Comment by SantaHey** [comment]
I tested with this code :
`from google_images_search import GoogleImagesSearch
gis = GoogleImagesSearch(api, cx)
from PIL import Image

search_params = {
    'q': 'test',
    'imgColorType': 'trans',
    'start' : 1,
    'num': 10
}

for i in range(101):
    gis.search(search_params=search_params)
    print(i)`

The 101th request stops with : "Quota exceeded for quota metric 'Queries' and limit 'Queries per day'
But I was wrong, it seems to NOT exceed quota quicker than with _'num':1_, you can forgot this part

However, I can change the 'start' param as I want, I always get the first image

**Comment by arrrlo** [comment]
Ok, I see.

That's not how you use it.
`start` param is used for paging.

Please read `Paging` section:
https://github.com/arrrlo/Google-Images-Search#paging

**Comment by SantaHey** [comment]
Ok, so 'start' param from cse api can't be used, right ?
https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list#body.QUERY_PARAMETERS.start

**Comment by arrrlo** [comment]
Yes, not for now.

**Comment by SantaHey** [comment]
Ok, thanks for answer
