### ISSUE TITLE
'NoneType' object has no attribute 'results'

### ISSUE THREAD

**Issue by turkunov** [arrrlo/Google-Images-Search#123]
When trying to access `.results()` with `query = 'Winston Churchill'` I'm getting `'NoneType' object has no attribute 'results'` error. I will appreciate any suggestions on a possible fix for this issue. Cheers.

Code:
```py
def get_image(query: str):
    cx = 'cx'  # identification of the search engine
    api_key = 'api'  # Google project api key
    search_params = {
        'q': query,
        'num': 1,
        'safe': 'high',
        'fileType': 'jpg|png',
        'imgType': 'photo',
    }
    gis = GoogleImagesSearch(api_key, cx)
    return gis.search(search_params=search_params).results() # crashes here
```

**Comment by Eddie-with-python** [comment]
Hey just asking what is a project cx? Sorry I am kind of new here.

**Comment by arrrlo** [comment]
Hi all,

> When trying to access `.results()` with `query = 'Winston Churchill'` I'm getting `'NoneType' object has no attribute 'results'` error. I will appreciate any suggestions on a possible fix for this issue. Cheers.

That's because `.search(...)` doesn't return anything.
It does the search, but saves the results in the `gis` object afterwards.
What you need to do is:
```python
gis = GoogleImagesSearch(api_key, cx)
gis.search(search_params=search_params)
return gis.results()
```


> Hey just asking what is a project cx? Sorry I am kind of new here.

It's the project identification.
That's how you tell Google API for which project do you query the API.
You have your project setup, quota, etc.

**Comment by turkunov** [comment]
I have not checked the checkmark for searching the whole web for the search engine. Thanks for keeping the project alive!
