### ISSUE TITLE
Is wildcard search possible ?

### ISSUE THREAD

**Issue by mobcdi** [arrrlo/Google-Images-Search#124]
Hiya, Your project looks exactly like what I need to compile a dataset of images from selected public websites. I hope you don't mind me asking but is it possible to use wildcards to return all images publicly available on a website and is it possible to get metadata about where in the site the image was found? 

I'm hoping to avoid having to create my own crawler to create an image dataset and think your project may be able to help 

Thanks

**Comment by arrrlo** [comment]
Hi @mobcdi,

Never thought about "scraping" entire websites for images.
I don't think Google allows using wildcards or something similar.
Though you can create CX only for desired website (not for the entire www) and download as many images using various keywords.

In hope this helps.
Cheers!

**Comment by mobcdi** [comment]
Yes thanks
