### ISSUE TITLE
Search results not compareble with realtime google search?

### ISSUE THREAD

**Issue by ABBOV** [arrrlo/Google-Images-Search#130]
Hello,

I've got the api call up and running, and i receive search results, thank you for that!
Only the search results I receive do not look anything like a regular image search in Google itself?

Is this something I can tweak in the _search_params? 
Even with the bear minimun of parameter, I get very different results

            _search_params = {
                'q': 'Litouwen Visaginas local cuisine eat',
                'num': 10,
                'fileType': 'jpg|gif|png',
            }

Any thoughts?

**Comment by teodora-petkova** [comment]
Hi!

I have also just tried the google search api and it is up and running. A great thank you from me, as well!

I am not sure whether it is a good remark but this is what I have found about the differences between the google searches [Google Search API Support](https://support.google.com/programmable-search/answer/2630972?hl=en)

> Image search results will vary from those returned by Google Images, even if you’ve configured your search engine to search the entire web. That's because Programmable Search Engine is designed to present a more personalized experience.

And another [discussion](https://stackoverflow.com/questions/48958387/google-customsearch-returns-different-result) on the matter:

> Your normal google search will be based on a lot of info that google picks up about you. If you sign out of google and use an incognito window, it should be unaffected.

I hope it helps a little bit at least!

**Comment by arrrlo** [comment]
Thank you @teodora-petkova for clarifying this 👍
