### ISSUE TITLE
No Images Found when using gimages search only

### ISSUE THREAD

**Issue by febrifahmi** [arrrlo/Google-Images-Search#150]
I'm trying to use the command (inside virtual environment) to search common images but it returns none. Here is the screenshot (the result is same for single keyword if I remove the apostrophe):

![image](https://user-images.githubusercontent.com/12995919/172301920-4d02024f-825a-4e4f-81d0-b99abb1211c9.png)

OS: Windows 10
Python version: Python 3.9.2
All Google API Key and Google CSE are already enabled.

**Comment by arrrlo** [comment]
Hi @febrifahmi 

Just tried with my api key and it's working fine:
```bash
>> gimages search -q "concrete structure"

GOOGLE IMAGES SEARCH 1.4.3

https://static.designboom.com/wp-content/dbsub/444870/2021-03-25/revolucionenelpatio-6-605c5812015ca.jpg
[image is not downloaded]
```

My first guess is that you misconfigured your custom search project.

Visit https://cse.google.com/cse/all and in the web form where you create/edit your custom search engine enable "Image search" option and for "Sites to search" option select "Search the entire web but emphasize included sites".

**Comment by febrifahmi** [comment]
Hi @arrrlo,

Sorry for my misunderstanding. I tried to set CSE as you suggested and finally, it's working fine. Thanks...
