### ISSUE TITLE
Can't specify image name using image.download

### ISSUE THREAD

**Issue by efeakaroz13** [arrrlo/Google-Images-Search#151]
I am trying to download google images but when I start the download it is giving me `OSError: [Errno 63] File name too long` error. Also I cant change the name of the file. Please help me with this situation.

**Comment by arrrlo** [comment]
Hi @efeakaroz13 

Can you please paste the search params and the code, and the complete error trace.

Also, if you want your images to be saved with different file name use this option:
https://github.com/arrrlo/Google-Images-Search#custom-file-name
