### ISSUE TITLE
Understanding quotas

### ISSUE THREAD

**Issue by andrea-gatto** [arrrlo/Google-Images-Search#152]
Hi,
from this guide
https://developers.google.com/custom-search/docs/overview
I see that there's a limit of 10k requests per day.
I guess the only way to increase this limit would be shifting towards a Custom Search Site Restricted JSON API (which has no limit) using 10 websites with a lot of images?

**Comment by arrrlo** [comment]
Hi @andrea-gatto 

Correct.
I never used it, so please try it out and let me know the results.

Thanks.
