### ISSUE TITLE
Please relax click version requirement, module works fine with 8.1.3

### ISSUE THREAD

**Issue by RomaKoks** [arrrlo/Google-Images-Search#154]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 2.2.2 requires click>=8.0, but you have click 7.1.2 which is incompatible.

**Comment by arrrlo** [comment]
Hi @RomaKoks 

This has been updated. Please update to the new version of this lib.

Cheers!
