### ISSUE TITLE
non-standard dependency specifier click>=7.0<=8.1.*.

### ISSUE THREAD

**Issue by mmccart3** [arrrlo/Google-Images-Search#175]
The new version of pip (24.1) rejects the installation with the following message:
DEPRECATION: google-images-search 1.4.6 has a non-standard dependency specifier click>=7.0<=8.1.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of google-images-search or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

Would someone kindly update line 47 of setup.py

**Comment by Paillat-dev** [comment]
@mmccart3 Here you go https://github.com/Paillat-dev/Google-Images-Search
just `pip install git+https://github.com/Paillat-dev/Google-Images-Search`

**Comment by larsblumberg** [comment]
@arrrlo would be great if you could make a new pypi release with the fix as it breaks all builds with recent pip versions.

**Comment by Paillat-dev** [comment]
@larsblumberg You can use my fork

**Comment by larsblumberg** [comment]
Thanks for the fix on your fork. As this is only a workaround (it requires `git` to be installed in the container), I'd be happy if @arrrlo could cherry-pick your fixing commit and release a new pypi package.

**Comment by Paillat-dev** [comment]
Right my bad. I will probably publish it to pypi too.

**Comment by arrrlo** [comment]
Hi all,

This is fixed. Pip doesn't break any more. New pypi version is live.
Sorry for delayed response.

**Comment by Paillat-dev** [comment]
Thanks, no problem.
