### ISSUE TITLE
Update click to 7+

### ISSUE THREAD

**Issue by marodev** [arrrlo/Google-Images-Search#25]
Hi Ivan, thank you for sharing your work!

Short question: May I ask you to update the dependency:

click==6.3

to 

click~=7 ?

**Comment by arrrlo** [comment]
Hi Martin,

Thanks for noticing.
This issue is totally on point.

Would you please create a pull request on this with all changes?
https://help.github.com/en/articles/creating-a-pull-request

Thank you.
