### ISSUE TITLE
Adding a rights param

### ISSUE THREAD

**Issue by nitinthewiz** [arrrlo/Google-Images-Search#36]
Hey,

I am looking at this list - https://developers.google.com/custom-search/v1/cse/list

and I realize that one of the crucial ones seems to be rights. 

Is it that unless we add that to the _search_params_keys, it’ll not be accepted as a parameter?

Or does your code accept arbitrary params? 

If the former, I can try to add rights as a key and send over a PR.

Thanks!

**Comment by arrrlo** [comment]
Hey @nitinthewiz,

Thanks for your contribution.
Feel free to add `rights` (or any other from the list) into `self. _search_params_keys` by creating pull request.

**Comment by arrrlo** [comment]
Hey @nitinthewiz,

still interested in this?

**Comment by nitinthewiz** [comment]
Thanks for closing this. I'll get to it at some point.
