### ISSUE TITLE
pipeline '|' in search params not working

### ISSUE THREAD

**Issue by sshaky2** [arrrlo/Google-Images-Search#37]
Following is my search param: 
```
_search_params = {
            'q': 'puppy',
            'num': 5,
            'safe': 'high',
            'fileType': 'jpg|png|gif',
            'imgSize': 'huge|icon|large|medium|small|xlarge|xxlarge',
            'searchType': 'image',
            'imgDominantColor': 'black'
        }
```
Error:
TypeError: Parameter "imgSize" value "huge|icon|large|medium|small|xlarge|xxlarge" is not an allowed value in "['huge', 'icon', 'large', 'medium', 'small', 'xlarge', 'xxlarge']"

**Comment by arrrlo** [comment]
Hi @sshaky2,

`'huge|icon|large|medium|small|xlarge|xxlarge'` is only an example of all possible size types.
Use one of them, like `huge`.

**Comment by sshaky2** [comment]
Thanks @arrrlo
