### ISSUE TITLE
not sure of to proceed with image size

### ISSUE THREAD

**Issue by chromafunk** [arrrlo/Google-Images-Search#42]
`TypeError: Parameter "imgSize" value "huge|large|xlarge|xxlarge" is not an allowed value in "['imgSizeUndefined', 'HUGE', 'ICON', 'LARGE', 'MEDIUM', 'SMALL', 'XLARGE', 'XXLARGE']"`

I get this exception, by following the documentation and writing this as search params :

```
        _search_params = {
            'q': f"{artist_name}",
            'num': 1-10,
            'safe': 'off',
            'fileType': 'jpg|png',
            'imgType': 'face|photo',
            'imgSize': 'huge|large|xlarge|xxlarge'
            }
```
Can you point out what's the problem here ? 

Thanks !

**Comment by arrrlo** [comment]
Hi @chromafunk ,

You can use only one image size per request, like this: `'imgSize': 'huge'`.
Meaning, you can't use multiple image sizes separated with pipe.
I used pipe sign only to list all possible sizes allowed to use. Same goes for `fileType` and `imgType`.

**Comment by chromafunk** [comment]
Actually I did take a look at the tests before you answered and tried with a single value but it still threw an error. I will try again and get back to you. Thanks !
