### ISSUE TITLE
Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by xiaoyongzhu** [arrrlo/Google-Images-Search#46]
This is a great project!

I am currently using it, but after it successfully downloaded a few images, I met this exception:

```
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000020135627A48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
```

Feel like Google might be throttling me but I've added sleep code and it doesn't work. Any ideas?

**Comment by arrrlo** [comment]
Hi @xiaoyongzhu,

Thank you for kind words.

Are you still experiencing issues regarding this?
Which version of the lib do you use?
