### ISSUE TITLE
When verify is enabled keep paging until num amount of correct images are found

### ISSUE THREAD

**Issue by Uskompuf** [arrrlo/Google-Images-Search#49]
This is tool is really great with its inbuilt URL verification however it means many results are skipped. For example, I just did `q:"dogs", num:"20"` and only got 8 results seeing that you have just added automatic pagination is it possible to extend this to attempt to get the num amount of verified images?

**Comment by arrrlo** [comment]
Yet, thought about that :)
Will let you know when I finish with that.
