### ISSUE TITLE
Can't set filename for downloaded image

### ISSUE THREAD

**Issue by otsir** [arrrlo/Google-Images-Search#50]
It would be very useful to have a option to set filename for downloaded image.

**Comment by arrrlo** [comment]
Hi @otsir,

Yes, sounds like a good thing to have.
Any suggestion on how to implement this? Maybe you can fork the repo and code the solution in separate branch and link it here?

**Comment by Xenophilicy** [comment]
I too would love to have this feature added as my image filenames are sometimes much too long and obnoxious.

**Comment by techguytechtips** [comment]
Please do, been trying to edit this library to name files but not much luck

**Comment by arrrlo** [comment]
Hey guys!
Finally got some time to do this.
Check the latest lib version.
