### ISSUE TITLE
Help needed. My code doesn't download the image.

### ISSUE THREAD

**Issue by Mr-burme** [arrrlo/Google-Images-Search#52]
Hi, I'm trying to get an image from the Creative Commons library using a custom Google search engine. I have selected the Creative Commons website in the sites to search list, but when I run the program it doesn't find any images. When I switched to search the whole web option the same thing happened.
I have got a super simple script:
gis = GoogleImagesSearch('My_key', ' Search engine ID ')

_search_params = {
    'q': 'dog',
    'num': 10,
    'safe': 'off',
    'fileType': 'png',
    'imgType': 'clipart',
    'imgSize': 'HUGE',
    'imgDominantColor': 'teal'
}

gis.search(search_params=_search_params)
print(gis.search(search_params=_search_params))

Output:
None #that is what it prints

Also if I don't care about some of the parameters should I leave them blank or are they obligatory? 

What am I doing wrong? Maybe my configuration is wrong?
It seems that the library is working correctly for other people so I want to thank you for creating this tool.
I hope you can help me.
Thanks!
Ernests

**Comment by arrrlo** [comment]
Hej @Mr-burme,

> It seems that the library is working correctly for other people so I want to thank you for creating this tool.  

No problem, the pleasure is mine as well.

> What am I doing wrong? Maybe my configuration is wrong?

I guess you missed on how to get photos urls after making a search.
This is how you do it:

```python
gis.search(search_params=_search_params)
for image in gis.results():
    ...
```

`gis.search()` doesn't return anything, it does the Google images search.
`gis.results()` is what you need, and you call it after `gis.search()`.

Please read the documentation again so you cal learn how to use the tool correctly:  
https://github.com/arrrlo/Google-Images-Search#programmatic-usage

I hope this helps.

**Comment by Mr-burme** [comment]
Thank you so much. Sorry for the stupid question.
Best of luck.
Ernests
