### ISSUE TITLE
View image url's

### ISSUE THREAD

**Issue by albertusgeyser** [arrrlo/Google-Images-Search#53]
Good Day

So glad to see someone made it possible to download images from google search.

I installed Google-Images-Search with pip and ran the command:

 **gimages search -q puppies -d /opt/ -w 500 -h 500 -s large**

To test and got the following:

 TypeError: Parameter "imgSize" value "large" is not an allowed value in "[u'imgSizeUndefined', u'HUGE', u'ICON', u'LARGE', u'MEDIUM', u'SMALL', u'XLARGE', u'XXLARGE']"

* Do i do something wrong as a test?
* How can i only return image url's?

Thank You

Albertus Geyser

**Comment by arrrlo** [comment]
fixed.
check latest lib version.
