### ISSUE TITLE
Using imgType lineart doesn't return any results

### ISSUE THREAD

**Issue by NodrogJRB** [arrrlo/Google-Images-Search#54]
When using the lineart term for the imgType parameter, no results seem to be downloaded. The code used is shown below:
```python
from google_images_search import GoogleImagesSearch

gis = GoogleImagesSearch('our_api_key', 'our_project_cx')

_search_params = {
	'q': 'house',
	'num': 1,
        'imgType': 'lineart'
}

gis.search(search_params=_search_params, path_to_dir='/home/administrator/Pictures/')
```
Without this search term the code functions as expected

**Comment by arrrlo** [comment]
Hej @NodrogJRB,

I made an update on the lib, just pip install latest version and try it out.

**Comment by NodrogJRB** [comment]
Hi @arrrlo,
Sorry for not replying to your original message! You were right about the increasing the number of images, we originally tried it with more but only up to around 5 or 10. Upon trying it with 50 we got plenty through but only 38 of them were downloaded so shows how many images are unavailable!

Will try out the updated lib when I get time thanks :)

**Comment by NodrogJRB** [comment]
Seems to work a lot better, will let you know if I run into any more issues with it!
