### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by techguytechtips** [arrrlo/Google-Images-Search#63]
There is no way of error handling The Quota exceeded for quota metric error raised by googleapiclient error inside the module
**`  File "googleapiclient\http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 429 when requesting https://customsearch.googleapis.com/customsearch/v1?cx=xxx=Ugh%2C&searchType=image&num=1&start=1&imgType=photo&fileType=jpg&safe=off&key=xxx&alt=json returned "Quota exceeded for quota metric 'Queries' and limit 'Queries per day' of service 'customsearch.googleapis.com'`**
Is there a way I can catch the Maximum Query's Per day instead of Excepting all errors the module could raise as Maximum Query's?

**Comment by arrrlo** [comment]
Hey @techguytechtips, try this:

```python

from googleapiclient.errors import HttpError

try:
    gis = GoogleImagesSearch('your_dev_api_key', 'your_project_cx')
    _search_params = { ... }
    gis.search(...)
except HttpError as e:
    ....

```

**Comment by techguytechtips** [comment]
> Hey @techguytechtips, try this:
> 
> ```python
> from googleapiclient.errors import HttpError
> 
> try:
>     gis = GoogleImagesSearch('your_dev_api_key', 'your_project_cx')
>     _search_params = { ... }
>     gis.search(...)
> except HttpError as e:
>     ....
> ```

Thank you for responding @arrrlo that worked
