### ISSUE TITLE
Not able to follow the instruction

### ISSUE THREAD

**Issue by shinokada** [arrrlo/Google-Images-Search#64]
In the README, 

Visit https://cse.google.com/cse/all and in the web form where you create/edit your custom search engine enable "Image search" option and for "Sites to search" option select "Search the entire web but emphasize included sites".

When I visit https://cse.google.com/cse/all, I get this page.

![image](https://user-images.githubusercontent.com/147320/90308157-0982d600-df18-11ea-8b6e-b31122a5c31b.png)

I clicked Add, then I get this. But it is not as you described in the README. What do I need to do?

![image](https://user-images.githubusercontent.com/147320/90308170-2919fe80-df18-11ea-8afd-1b9fc0f482c5.png)

Thanks.

**Comment by khushhalm** [comment]
Hi, @shinokada I think the documentation is old. What you can do is add any site and then you will get all those options.
