### ISSUE TITLE
After a SSLError It no longer saves images with a custom filename

### ISSUE THREAD

**Issue by techguytechtips** [arrrlo/Google-Images-Search#69]
if you have a for loop to download multiple images and it tries to download a word and gets a SSLError all the images it downloads afterwards will not have a custom filename (this is sample code)
`arr = ["test", "Hey", "Heavy"]`
`for word in arr:`
    `_search_params['q'] = arr[i]`
   ` try:`
        `gAPI.search(search_params=_search_params, path_to_dir="ImageCache", custom_image_name=str(i))`
    `except Exception as e:`
        `print(e)`
    `i += 1`
![image](https://user-images.githubusercontent.com/33581259/91355948-e3cdba80-e7bc-11ea-841b-78f52bf86737.png)

### Expected Behavior:
After the SSLError it continues to save files with a custom image name
### Actual Behavior:
Continues to download Images but without a custom image name.
My guess is because it does not delete the failed image that had the SSLError
it fails to make a new image of that name because the image already exists because it has a custom file name and instead just makes the filename the URL instead of the custom file name because it already exists.

**Comment by arrrlo** [comment]
Hey @techguytechtips ,

Thanks for submitting.
This is fixed now.
Check latest lib version.
