### ISSUE TITLE
I can’t get it to work

### ISSUE THREAD

**Issue by HalpINeedHalp** [arrrlo/Google-Images-Search#73]
I am sorry I am very stoopid and I can’t seem like to get this right. Where can I download the image for the path to get it to my project or have it locally downloaded would be best. Again not very smart
I am going to add a little thingy to this thread on my pc cause I am on my phone rn

**Comment by HalpINeedHalp** [comment]
from google_images_search import GoogleImagesSearch
gis = GoogleImagesSearch('My_Key', 'Search_engine_id')


# define search params:
_search_params = {
    'q': 'puppy',
    'num': 10,
    'safe': 'high',
    'fileType': 'jpg',
    'imgType': 'clipart',
    'imgSize': 'HUGE',
    'imgDominantColor': 'white',
    'usageRights': 'cc_publicdomain'
}

# this will only search for images:
gis.search(search_params=_search_params)
for image in gis.results():
    image.download('/drive/my-drive') #what do i do here???<------- to like actually get it i am on windows also

**Comment by HalpINeedHalp** [comment]
I made my search engine google and i tried the program in powershell and it returned no images found i had only my api key and search engine number letter thing as envirormental variables and i was searching for puppies i feel there is no way there wasnt a single image.

**Comment by HalpINeedHalp** [comment]
nevermind i messed up some settings on my browser thanks so much

**Comment by HalpINeedHalp** [comment]
sorry i still cant download them automatically i feel so stupid rn
pls help when u can any1

**Comment by techguytechtips** [comment]
hey @HalpINeedHalp. does it give you a error or anything that could hint to what may be wrong? Please include the current code that you are using and we will go from there

**Comment by HalpINeedHalp** [comment]
Sorry forgot to close it got something working that is good enough
