### ISSUE TITLE
urllib3 warning : InsecureRequestWarning: Unverified HTTPS request

### ISSUE THREAD

**Issue by jrmbr** [arrrlo/Google-Images-Search#74]
Hey,

First let me thank you for the very useful package ! I started using it recently and everything works fine, but I keep getting the following warning when running the search function: 

"InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)"

Any idea where it comes from/ how to fix it ? Any help would be welcome !

Thanks again

jeremy

**Comment by arrrlo** [comment]
Hey @jrmbr,

Thank you for kind words.

I know exactly where is this coming from.
I'll fix it and let you know.

**Comment by arrrlo** [comment]
Could you please post the exact search params you're using. Thanks.

**Comment by OskarWalichniewicz** [comment]
```
from google_images_search import GoogleImagesSearch

gis = GoogleImagesSearch('dev_api_key', 'project_cx')

_search_params = {
    'q': 'parachute',
    'num': 5
}

gis.search(search_params = _search_params)

for result in gis.results():
    print(result.get_raw_data())
```

`\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "c:/Users/oskar/Desktop/gsearch.py", line 13, in <module>
    print(result.get_raw_data())
  File "C:\Users\oskar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google_images_search\fetch_resize_save.py", line 374, in get_raw_data
    return b''.join(list(self._fetch_resize_save.get_raw_data(self._url)))
  File "C:\Users\oskar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\google_images_search\fetch_resize_save.py", line 271, in get_raw_data
    with requests.get(url, stream=True, verify=False) as req:
AttributeError: __enter__`

Whatever parameters I've tried I get the same error as OP. Works fine from CLI.

**Comment by jrmbr** [comment]
I'm doing : 

gc = client.GoodreadsClient(key, secret)
_search_params = {'q': title + additional_arguments,'num': 5,'fileType': 'jpg',}
gis.search(search_params=_search_params, path_to_dir=localimagesPath)

**Comment by arrrlo** [comment]
Hey @jrmbr ,

This is fixed now.
Check new lib version, 1.3.3
