### ISSUE TITLE
results are different from google image top results

### ISSUE THREAD

**Issue by LamyaMohaned** [arrrlo/Google-Images-Search#77]
Hello, the code works with me, but the problem is that the retrieved images are different from google image search top results. sometimes the code returns irrelevant images

**Comment by arrrlo** [comment]
Hi,

Have you tried to set exactly the same parameters when using a web search, like image size, etc?

**Comment by sina-ehsani** [comment]
Hi,
Thanks for the great work. It is very useful. 
I also had same question as LamyaMohaned, the results are not same as images retrieved using a browser. I used the same parameters, but no luck. Do you have any ideas on why this happens ?
Thank you.

**Comment by arrrlo** [comment]
Hi @sina-ehsani,

I can just assume that Google intentionally gives one set of results on their web site and another/different through their API.
All sorts of reasons could be included here, like different caching for web comparing to API or different privacy policy for web and for API, etc.
This library literary cannot affect search results coming from Google's API.
There is only one thing. Validation: https://github.com/arrrlo/Google-Images-Search#image-validation
So if the image fails in validation, it will not be included in final result list coming from this lib.

Also, did you use CLI or programable?
