### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by manikamittal2898** [arrrlo/Google-Images-Search#84]
Hey, everytime I run- from google_images_search import GoogleImagesSearch, I am shown the following error: 

![image](https://user-images.githubusercontent.com/31413782/100556463-9f285280-32c8-11eb-8689-de0e70a319d3.png)
![image](https://user-images.githubusercontent.com/31413782/100556474-ae0f0500-32c8-11eb-8bb2-15241375ab01.png)
Could you please help me? I have tried reinstalling google_core.api multiple times but I am still unable to use this api. Thank you in advance.

**Comment by arrrlo** [comment]
Hi @manikamittal2898,

Have you managed to solve this?

**Comment by manikamittal2898** [comment]
Hey @arrrlo 
Unfortunately, despite all my efforts, I haven''t been able to resolve this issue

**Comment by manikamittal2898** [comment]
Do you have any suggestion or any idea of the possible cause of the error?

**Comment by arrrlo** [comment]
Hi @manikamittal2898,

Just googled it and this is the first result:
https://stackoverflow.com/questions/57118925/no-module-named-google-api-core-client-options-while-importing-firestore

Hope it helps.
