### ISSUE TITLE
Continuously return results of the first search

### ISSUE THREAD

**Issue by Zazarr** [arrrlo/Google-Images-Search#86]
The engine continuously return results of the very first search even if I set `cache_discovery=False` in params:

```
search_params = {
            'q': query,
            'num': 20,
            'safe': 'off'
        }
```

`gis.search(search_params=search_params, cache_discovery=False)`

BTW query is not the same in each trying - it's visually noticeable in code debugging (I'm once a several minutes getting random url from first 20 results from random word of word list).

**Comment by Zazarr** [comment]
A temporary solution is to rewrite the following lines by hand right in the code:

https://github.com/arrrlo/Google-Images-Search/blob/95b1b969a3a7c4d9c7e8ab83b25cadcc74f75979/google_images_search/google_api.py#L34

– def _query_google_api(self, search_params, cache_discovery=True):
➕ def _query_google_api(self, search_params, **cache_discovery=False**):

https://github.com/arrrlo/Google-Images-Search/blob/95b1b969a3a7c4d9c7e8ab83b25cadcc74f75979/google_images_search/fetch_resize_save.py#L53
– def _set_data(self, search_params=None, path_to_dir=False,
–                  width=None, height=None, cache_discovery=True):

➕ def _set_data(self, search_params=None, path_to_dir=False,
➕                width=None, height=None, **cache_discovery=False**):

**Comment by arrrlo** [comment]
Hi,

Are you sure with this?

Here is the code I used now to test this:

```python
_search_params = {
    'q': 'test',
    'num': 20,
    'safe': 'off'
}
gis.search(search_params=_search_params, cache_discovery=False)

print('page 1')
for image in gis.results():
    print(image.url)

gis.next_page()

print('page 2')
for image in gis.results():
    print(image.url)
```

And this is the result:

page 1
http://p5cdn4static.sharpschool.com/UserFiles/Servers/Server_3168824/Image/test.png
https://developers.google.com/admob/images/ios-testad-0.png
https://lh3.googleusercontent.com/aNKNmmUADALFnQF1wKHLJvHm4PQZpWyy8q4vSQHEMlU2E2emh7FdbZVYoLq6r6l1bQ4K=w450-rwa
https://i.ytimg.com/vi/_IRVa8daR3Y/hqdefault.jpg
https://lh3.googleusercontent.com/f_8UlCKTLeZkETJUzCxW5UiQerDhRbJyqQKtdSw8bf72HswTkyOZ9usdp0UmJc18xg=w450-rwa
https://www.test.com/img/Gauge-computer.png
https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iMZsC0LX5xtk/v1/1000x-1.jpg
https://www.jhsph.edu/sebin/z/b/antibody-testing_820x440.jpg
https://cdn.cnn.com/cnnnext/dam/assets/200724205055-standardized-test-bubble-sheet-stock-large-169.jpg
https://play-lh.googleusercontent.com/1sJBdkr_0ORFtvtpMCaYPOoDmOTq3nbYHthtocHjgniQtJ9GkEQXHcyPWB05OByDL98k=w412-h220-rw
https://www.outbrain.com/techblog/wp-content/uploads/2017/05/road-sign-361513_960_720.jpg
https://www.investopedia.com/thmb/r08LOvu42fQKmksInXTGbhyf9jE=/6164x4623/smart/filters:no_upscale()/ttest22-0afd4aefe9cc42628f603dc2c7c5f69a.png
https://play-lh.googleusercontent.com/0bMoW7QDccU11zJsfw61RvB1yfM0adw4DyrqnOcuBXIB_PM8tWYQybjtuEI83tBz7MsV=w412-h220-rw
https://lh3.googleusercontent.com/apj2QxjAbpSV84C8UCkx8KcgPBibHwVNnifM2MhAlsrV7xQQJ0e1nr2v9JiMKLy1BdfqKx219k2homi3ncxWJb2gC4A=w640-h400-e365-rj-sc0x00ffffff
https://upload.wikimedia.org/wikipedia/commons/4/49/Urine_pregnancy_test_%28positive%29.png
https://lh3.googleusercontent.com/tKAGAzRvYjgVs9sbpDxKQohMSNkJUIAMJ6C6f6IWyCpfRX0GgrcA1Rf-RbJmu_ZFLBjMOt283zQw1XbTGQkfpBjzRg0=w640-h400-e365-rj-sc0x00ffffff
https://hatrabbits.com/wp-content/uploads/2018/10/risky-assumptions.jpg
https://i0.wp.com/post.healthline.com/wp-content/uploads/2020/11/Lucira_Covid_Test_1296x728-header-1-1296x729.jpg?w=1155&h=2268
https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Test-Logo.svg/783px-Test-Logo.svg.png
https://spectrum.ieee.org/image/MzU4OTU0MA.jpeg
page 2
https://i.ytimg.com/vi/Gsd26EuSg4g/maxresdefault.jpg
https://miro.medium.com/max/2800/0*xMaFF2hSXpf_kIfG.jpg
https://news.uchicago.edu/sites/default/files/styles/full_width/public/images/2018-05/sjyeprhvxi1007820110114.jpg?itok=rWr_JB4t
https://www.insidehighered.com/sites/default/server_files/media/Getty/standardized%20test.jpg
https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/other/covid_19_antibody_strip_test_other/1800x1200_covid_19_antibody_strip_test_other.jpg
https://i.ytimg.com/vi/LYi19-Vx6go/maxresdefault.jpg
https://asm.org/getmedia/f3314516-a719-4c40-9558-5effc5f81e51/Antigen-Testing.png?width=592&height=333&ext=.png
https://res.cloudinary.com/babylist/image/upload/f_auto,q_auto:best,c_scale,w_1200/v1561148722/hello-baby/best-pregnancy-tests-to-take-header.jpg
https://dreamix.eu/blog/wp-content/uploads/2017/05/20150224test644-1508x706_c.jpg
https://media.self.com/photos/58a1fc2469f21ba607c78cd3/3:4/w_710,h_947,c_limit/false-positive-test.jpg
https://www.123test.com/iq-test/screenshots/6.png
https://www.mainstreetfamilycare.com/wp-content/uploads/2020/07/covid19-laboratory-test-report-picture-id1222920564-1.jpg
https://upload.wikimedia.org/wikipedia/commons/5/55/Turing_test_diagram.png
https://m.media-amazon.com/images/M/MV5BYzc3OGZjYWQtZGFkMy00YTNlLWE5NDYtMTRkNTNjODc2MjllXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_UY1200_CR114,0,630,1200_AL_.jpg
https://structureofintellect.files.wordpress.com/2017/09/bubble-test.jpg
https://www.verywellmind.com/thmb/_7t8QdlE78WuqRlqke0ucPHEAe0=/500x350/filters:no_upscale():max_bytes(150000):strip_icc()/183760060-56a795b93df78cf772976175.jpg
https://play-lh.googleusercontent.com/YNMfyhkMgsJuzmkjyr14lu1lgXtLu0Mvap5_Qpzf1svw4pmYMaZkGA27Z5zn_v6-NMqZ
https://www.verywellfamily.com/thmb/XiHWahp5R9PFgM0KT0D2HSOqy6Q=/500x350/filters:no_upscale():max_bytes(150000):strip_icc()/pregnancy-test-accuracy-596cdbe0aad52b0011f88683.png
https://www.networkforgood.com/wp-content/uploads/2015/08/bigstock-Test-word-on-white-keyboard-27134336.jpg
https://uhs.umich.edu/files/uhs/field/image/TEST.jpg

**Comment by Zazarr** [comment]
> ```python
> _search_params = {
>     'q': 'test',
>     'num': 20,
>     'safe': 'off'
> }
> gis.search(search_params=_search_params, cache_discovery=False)
> 
> print('page 1')
> for image in gis.results():
>     print(image.url)
> ```

Hmm. I had to write the procedures myself. Now I tried to remember what was there. And it seems to me that the code for verification should have been like this.

_search_params = {
    'q': 'test',
    'num': 20,
    'safe': 'off'
}
gis.search(search_params=_search_params, cache_discovery=False)

print('Searching 1 query...')
for image in gis.results():
    print(image.url)

_search_params = {
    'q': 'Paraguay capital',
    'num': 20,
    'safe': 'off'
}
gis.search(search_params=_search_params, cache_discovery=False)

print('Searching 2nd query...')
for image in gis.results():
    print(image.url)

On the second cycle of printing links, I did not get a different result, but the same one.

P.S. For     'num': 20, - Gogle doesn't allow set this more than 10 for one page. As far as I remember.

**Comment by arrrlo** [comment]
That is not possible for lib (and Google lib as well) to give exactly the same results for different query.
It should have been made as a feature to remember results from the first run, and that wasn't the case.
I just tried it out and it gave two sets of different image links.

And yes, Google accepts only `num: 10` per one query.
But this lib in the case of 20, for example, does two requests in the background, and three requests when querying 21 images, and so on.
You can easily put `num:765`, but you'll probably hit the daily Google API limit.
