### ISSUE TITLE
The code does not know how to handle Max retries exceeded error

### ISSUE THREAD

**Issue by Zazarr** [arrrlo/Google-Images-Search#88]
The code does not know how to handle Max retries exceeded error. Sometimes this happens when program with GSI actively access a site, and it blocks for exceeding the number of hits per unit of time. We get this error:
**HTTPSConnectionPool(host='gate.undelete.news', port=443): Max retries exceeded with url -----** there valid URL with valid picture.

**Comment by arrrlo** [comment]
Did you handle it somehow by now?

I don't think this lib should deal with this because you want this exception to be risen and informs you that you should have bigger Google API limit.
The worst case scenario would be for this problem to silently fail.
