### ISSUE TITLE
A question about API key

### ISSUE THREAD

**Issue by crvenkapica0** [arrrlo/Google-Images-Search#90]
dear all,

I have a problem when I run the following code:
_gis.search(search_params=_search_params, path_to_dir='/path/', width=500, height=500)_

and the error I get is:
_HttpError: <HttpError 400 when requesting https://www.googleapis.com/discovery/v1/apis/customsearch/v1/rest?key=your_dev_api_key returned "API key not valid. Please pass a valid API key.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_INVALID', 'domain': 'googleapis.com', 'metadata': {'service': 'customsearch.googleapis.com'}}]">_

Any idea what went wrong?

**Comment by Nauais** [comment]
have you created an API key with the google's tools ?

**Comment by arrrlo** [comment]
Hi @crvenkapica0,

Have you gone through this Installation process and generated an API key and set a project?
https://github.com/arrrlo/Google-Images-Search#installation
