### ISSUE TITLE
fileType specifier appears to be broken

### ISSUE THREAD

**Issue by LuckyStripe** [arrrlo/Google-Images-Search#92]
Hello,
I am experimenting with this module and found that even though in _search_params i specified 
`'fileType': 'png'`
it still safes as jpg. The same seems to happen for
`'fileType': 'gif'`

Kind regards

**Comment by arrrlo** [comment]
Hi,

Are you sure?
Just tried with a number of different queries and a lot if images being pulled and all with same image extensions.

**Comment by LuckyStripe** [comment]
I didn't pull hundrets of images but for me it always converted to jpg. 
I am using this for a discord bot and changed it to url a day later, after I discovered how to get the url.
With urls it's working great so far.
Maybe it was actually caused by something else, in that case I'm sorry for wasting your time.

**Comment by arrrlo** [comment]
No problem.
Happy to hear it's working fine now.
Closing this issue.
