### ISSUE TITLE
Query language.

### ISSUE THREAD

**Issue by iacercalixto** [arrrlo/Google-Images-Search#93]
It looks like I can only search using queries written in English, is that so? If it is, how to include an additional parameter in the search query to account for the query language? Thanks!

**Comment by arrrlo** [comment]
you mean query as when you enter a phrase in `q` key?:
```python
_search_params = {
    'q': '...',
}
```

google doesn't care which language you are using.
use any language you want.

**Comment by ZobaJakColbert** [comment]
Hi, I want to find images with query "pies" in polish. But in polish pies means dog, and in english it's plural of pie. How to get pictures based of language?

I tried add to search_params
            'lr': 'pl',
            'hl': 'pl',
            'gl': 'pl',
            
            but it doesn't work
